In [2]:
1+1

2

In [ ]:
import numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [17]:
lst_1 = [1,2,3,4,5]
lst_2 = [6,7,8,9,10]
lst_3 = [11,12,13,14,15]
arr = np.array([lst_1, lst_2, lst_3])
print(arr)
type(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


numpy.ndarray

In [19]:
arr.shape

(3, 5)

In [20]:
arr1 = arr.reshape(5,3)

In [23]:
arr1.shape
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [26]:
#indexing
arr1[2:,:2]

array([[ 7,  8],
       [10, 11],
       [13, 14]])

In [31]:
arr2 = np.arange(0,10, step=2)
arr2

array([0, 2, 4, 6, 8])

In [28]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [33]:
#copy function 
arr3 = arr2.copy()
arr4 = arr2.reshape(5,1)

print(arr3, arr4)

[0 2 4 6 8] [[0]
 [2]
 [4]
 [6]
 [8]]


In [34]:
np.random.rand(3,3)

array([[0.40552811, 0.7736932 , 0.19149795],
       [0.0127131 , 0.12640852, 0.45763704],
       [0.95834843, 0.5877472 , 0.52188963]])

In [42]:
#pandas
import pandas as pd
import numpy as np

#dataframe
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=['Column1', 'Column2', 'Column3', 'Column4'])

In [36]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [38]:
df.to_excel('Test1.xlsx')

In [47]:
#accessing the elements
# 1. .loc 2. .iloc
df.loc['Row1']
type(df.loc['Row1'])

pandas.core.series.Series